---
title: "Summary report"
output:
  html_document: default
  word_document: default
---


```{r}
country <- "Ghana"  # choices "Ghana", "Liberia", "Sierra Leone"

# Here you need to specifiy the full path name:
input.file.name <- "/home/einarhj/prj2/unuftp/VMS-training-2018/Training folders/Ghana/Layers/VMS data files/Workshop Data/march 18.csv"

output.file.name <- "2018-05-28_output.csv"  
gridded.file.name <- "2018-05-28_output-gridded.csv"

lon.min <- -15
lon.max <- 2.5

lat.min <- 3.0
lat.max <- 10

speed.min <- 2.5
speed.max <- 4.5
speed.extreme <- 15 # Above this speed the histogram is not plotted

# date should be valid YYYY-MM-DD HH:MM.SS
date.min <- "2000-01-01 00:00:00"
date.max <- "2100-12-31 23:59:00"

grid.resolution <- 0.05   # Decimal degree units
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
# Needed libaries
library(knitr)
library(tidyverse)
library(lubridate)
library(rio)
library(sp)
library(raster)

# Some helper functions
grade <- function(x, dx) {
  brks <- seq(floor(min(x)), ceiling(max(x)),dx)
  ints <- findInterval(x, brks, all.inside = TRUE)
  x <- (brks[ints] + brks[ints + 1]) / 2
  return(x)
}

vms_import_data <- function(file.name, country, speed.min, speed.max, date.min, date.max) {
  
  if(country == "Ghana") {
    import(file.name) %>%
      rename(vid = Mobile,
             date = Date,
             lon = Longitude,
             lat = Latitude,
             speed = Speed) %>% 
      mutate(date = dmy_hms(date),
             activity = case_when(speed < speed.min ~ paste0("<", speed.min),
                                  speed < speed.max ~ paste0(speed.min, "-", speed.max),
                                  TRUE ~ paste0(">", speed.max))) %>% 
      filter(between(date, ymd_hms(date.min), ymd_hms(date.max))) %>% 
      return()
  }

  if(country == "Sierra Leone") {
    import(file.name) %>%
      rename(vid = PublicDeviceID,
             date = gpsTime,
             lon = Lon,
             lat = Lat,
             speed = Speed) %>%
      mutate(date = str_sub(gpsTime, 1, 19),
             date = ymd_hms(date),
             speed = as.numeric(speed) * 3600/185200,
             activity = case_when(speed < speed.min ~ paste0("<", speed.min),
                                  speed < speed.max ~ paste0(speed.min, "-", speed.max),
                                  TRUE ~ paste0(">", speed.max))) %>%
      filter(between(date, ymd_hms(date.min), ymd_hms(date.max))) %>%
      return()
  }

}

vms_plot_speed <- function(d, bindwidth = 0.5, speed.min = 0, speed.max = 15) {
  d %>%
    dplyr::select(speed) %>%
    tidyr::drop_na() %>%
    dplyr::mutate(speed = grade(speed, bindwidth)) %>%
    dplyr::group_by(speed) %>%
    dplyr::count() %>%
    dplyr::mutate(activity = ifelse(dplyr::between(speed, speed.min, speed.max),
                                    "Fishing",
                                    "Not Fishing")) %>%
    ggplot2::ggplot(ggplot2::aes(speed, n, fill = activity)) +
    ggplot2::geom_col()
}

vms_filter_data <- function(d,
                            lon.min = -179, lon.max = 179,
                            lat.min = -89,  lat.max = 89,
                            speed.min = 2.5, speed.max = 4.5,
                            date.min = date.min, date.max = date.max) {

  d %>%
    dplyr::select(lon, lat, speed) %>%
    tidyr::drop_na() %>%
    dplyr::filter(dplyr::between(lon, lon.min, lon.max),
                  dplyr::between(lat, lat.min, lat.max),
                  dplyr::between(speed, speed.min, speed.max))

}

vms_grid_data <- function(d, dx, dy) {

  if(missing(dx)) stop("You need to provide the longitudinal resolution")

  if(missing(dy)) dy <- dx

  d %>%
    dplyr::select(lon, lat) %>%
    tidyr::drop_na() %>%
    dplyr::mutate(lon = grade(lon, dx),
                  lat = grade(lat, dy)) %>%
    dplyr::group_by(lon, lat) %>%
    dplyr::count() %>%
    dplyr::ungroup()

}

# Alternative using the raster package... need this for saving as GeoTIFF
vms_grid_data2 <- function(d, dx, dy) {

  if(missing(dx)) stop("You need to provide the longitudinal resolution")

  if(missing(dy)) dy <- dx

  d %>%
    dplyr::select(lon, lat) %>%
    tidyr::drop_na()

  # Convert to SpatialPoints
  coordinates(d) <- c("lon", "lat")
  proj4string(d) <- "+proj=longlat"

  # Rasterization
  rst <- raster(xmn = min(d$lon),
             xmx = max(d$lon),
             ymn = min(d$lat),
             ymx = max(d$lat),
             res = grid.resolution,
             crs = "+proj=longlat")
  rst <- rasterize(d, rst, field = 1, fun = "count")
  return(rst)
}


vms_plot_grid <- function(d, limit.upper = 0.99) {

  require(mapdata)
  m <-
    ggplot2::map_data("worldHires",
                      xlim = range(d$lon),
                      ylim = range(d$lat))

  d %>%
    dplyr::mutate(n = ifelse(n > quantile(n, limit.upper),
                             quantile(n, limit.upper),
                             n)) %>%
    ggplot2::ggplot() +
    ggplot2::geom_polygon(data = m, aes(long, lat, group = group), fill = "grey") +
    ggplot2::geom_raster(ggplot2::aes(lon, lat, fill = n)) +
    ggplot2::coord_quickmap(xlim = range(d$lon), ylim = range(d$lat)) +
    viridis::scale_fill_viridis(option = "B", direction = -1) +
    ggplot2::scale_x_continuous(name = NULL) +
    ggplot2::scale_y_continuous(name = NULL)

}

```


```{r}
# Import data
vms.raw <-
  vms_import_data(input.file.name,
                  country = country,
                  speed.min = speed.min,
                  speed.max = speed.max,
                  date.min = date.min,
                  date.max = date.max)
```

## Summary of the VMS data

```{r}
# Einar will work further on this
vms.raw %>% summary()
```

## Summary of activity by vessel

```{r}
vms.raw %>% 
  group_by(vid, activity) %>% 
  count() %>% 
  spread(activity, n) %>% 
  kable()
```

```{r}
vms.filtered <- 
  vms_filter_data(vms.raw,
                  lon.min = lon.min,
                  lon.max = lon.max,
                  lat.min = lat.min,
                  lat.max = lat.max,
                  speed.min = speed.min,
                  speed.max = speed.max)
vms.raw %>% 
  filter(speed < speed.extreme) %>%
  vms_plot_speed(speed.min = speed.min,
                 speed.max = speed.max)
vms.grid <- 
  vms.filtered %>% 
  vms_grid_data(dx = grid.resolution)
vms_plot_data(vms.grid)
```

